### ISSUE TITLE
The box 'puppetlabs/centos-6.6-64-puppet' could not be found

### ISSUE THREAD

**Issue by Openet-Labs** [Openet-Labs/vagrant-enigma#1]
You may see this error when running `vagrant up` on OSX

    $ vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Box 'puppetlabs/centos-6.6-64-puppet' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 1.0.1
    The box 'puppetlabs/centos-6.6-64-puppet' could not be found or
    could not be accessed in the remote catalog. If this is a private
    box on HashiCorp's Atlas, please verify you're logged in via
    `vagrant login`. Also, please double-check the name. The expanded
    URL and error message are shown below:
    
    URL: ["https://atlas.hashicorp.com/puppetlabs/centos-6.6-64-puppet"]
    Error:

This is a known Vagrant issue. See [here](https://github.com/mitchellh/vagrant/issues/7969) for the workaround

**Comment by glockhart** [comment]
Closing as there's a known workaround . https://github.com/mitchellh/vagrant/issues/7969
